name: Local README Stats
on:
  schedule:
    - cron: "43 14 * * *"   # roda todo dia 11:43 (America/Sao_Paulo = UTC-3)
  workflow_dispatch:
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - name: Install deps
        run: pip install -r requirements.txt
      - name: Generate cards
        run: python tools/gen_readme_cards.py
      - name: Commit changes
        run: |
          if [ -n "$(git status --porcelain cards/*.svg 2>/dev/null)" ]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add cards/*.svg
            git commit -m "chore: update local readme stats cards"
            git push
          fi

